/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MusicRouteImport } from './routes/music'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as StreamingRouteImport } from './routes/streaming'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as WorkRouteImport } from './routes/work'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as InfoSlugRouteImport } from './routes/info.$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as OriginalsIndexRouteImport } from './routes/originals.index'
import { Route as OriginalsSlugRouteImport } from './routes/originals.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as TourBtsArirangRouteImport } from './routes/tour.bts-arirang'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingRoute = StreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoSlugRoute = InfoSlugRouteImport.update({
  id: '/info/$slug',
  path: '/info/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginalsIndexRoute = OriginalsIndexRouteImport.update({
  id: '/originals/',
  path: '/originals/',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginalsSlugRoute = OriginalsSlugRouteImport.update({
  id: '/originals/$slug',
  path: '/originals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TourBtsArirangRoute = TourBtsArirangRouteImport.update({
  id: '/tour/bts-arirang',
  path: '/tour/bts-arirang',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/culture': typeof CultureRoute
  '/explore': typeof ExploreRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/music': typeof MusicRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sports': typeof SportsRoute
  '/streaming': typeof StreamingRoute
  '/trends': typeof TrendsRoute
  '/work': typeof WorkRoute
  '/admin/$': typeof AdminSplatRoute
  '/info/$slug': typeof InfoSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/originals/$slug': typeof OriginalsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/tour/bts-arirang': typeof TourBtsArirangRoute
  '/news/': typeof NewsIndexRoute
  '/originals/': typeof OriginalsIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/culture': typeof CultureRoute
  '/explore': typeof ExploreRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/music': typeof MusicRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sports': typeof SportsRoute
  '/streaming': typeof StreamingRoute
  '/trends': typeof TrendsRoute
  '/work': typeof WorkRoute
  '/admin/$': typeof AdminSplatRoute
  '/info/$slug': typeof InfoSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/originals/$slug': typeof OriginalsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/tour/bts-arirang': typeof TourBtsArirangRoute
  '/news': typeof NewsIndexRoute
  '/originals': typeof OriginalsIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/culture': typeof CultureRoute
  '/explore': typeof ExploreRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/music': typeof MusicRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sports': typeof SportsRoute
  '/streaming': typeof StreamingRoute
  '/trends': typeof TrendsRoute
  '/work': typeof WorkRoute
  '/admin/$': typeof AdminSplatRoute
  '/info/$slug': typeof InfoSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/originals/$slug': typeof OriginalsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/tour/bts-arirang': typeof TourBtsArirangRoute
  '/news/': typeof NewsIndexRoute
  '/originals/': typeof OriginalsIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/culture'
    | '/explore'
    | '/games'
    | '/login'
    | '/music'
    | '/reset-password'
    | '/signup'
    | '/sports'
    | '/streaming'
    | '/trends'
    | '/work'
    | '/admin/$'
    | '/info/$slug'
    | '/news/$slug'
    | '/originals/$slug'
    | '/shop/$slug'
    | '/tour/bts-arirang'
    | '/news/'
    | '/originals/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/culture'
    | '/explore'
    | '/games'
    | '/login'
    | '/music'
    | '/reset-password'
    | '/signup'
    | '/sports'
    | '/streaming'
    | '/trends'
    | '/work'
    | '/admin/$'
    | '/info/$slug'
    | '/news/$slug'
    | '/originals/$slug'
    | '/shop/$slug'
    | '/tour/bts-arirang'
    | '/news'
    | '/originals'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/culture'
    | '/explore'
    | '/games'
    | '/login'
    | '/music'
    | '/reset-password'
    | '/signup'
    | '/sports'
    | '/streaming'
    | '/trends'
    | '/work'
    | '/admin/$'
    | '/info/$slug'
    | '/news/$slug'
    | '/originals/$slug'
    | '/shop/$slug'
    | '/tour/bts-arirang'
    | '/news/'
    | '/originals/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CultureRoute: typeof CultureRoute
  ExploreRoute: typeof ExploreRoute
  GamesRoute: typeof GamesRoute
  LoginRoute: typeof LoginRoute
  MusicRoute: typeof MusicRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SportsRoute: typeof SportsRoute
  StreamingRoute: typeof StreamingRoute
  TrendsRoute: typeof TrendsRoute
  WorkRoute: typeof WorkRoute
  AdminSplatRoute: typeof AdminSplatRoute
  InfoSlugRoute: typeof InfoSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  OriginalsSlugRoute: typeof OriginalsSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  TourBtsArirangRoute: typeof TourBtsArirangRoute
  NewsIndexRoute: typeof NewsIndexRoute
  OriginalsIndexRoute: typeof OriginalsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming': {
      id: '/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof StreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/$slug': {
      id: '/info/$slug'
      path: '/info/$slug'
      fullPath: '/info/$slug'
      preLoaderRoute: typeof InfoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/originals/': {
      id: '/originals/'
      path: '/originals'
      fullPath: '/originals/'
      preLoaderRoute: typeof OriginalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/originals/$slug': {
      id: '/originals/$slug'
      path: '/originals/$slug'
      fullPath: '/originals/$slug'
      preLoaderRoute: typeof OriginalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/bts-arirang': {
      id: '/tour/bts-arirang'
      path: '/tour/bts-arirang'
      fullPath: '/tour/bts-arirang'
      preLoaderRoute: typeof TourBtsArirangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CultureRoute: CultureRoute,
  ExploreRoute: ExploreRoute,
  GamesRoute: GamesRoute,
  LoginRoute: LoginRoute,
  MusicRoute: MusicRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SportsRoute: SportsRoute,
  StreamingRoute: StreamingRoute,
  TrendsRoute: TrendsRoute,
  WorkRoute: WorkRoute,
  AdminSplatRoute: AdminSplatRoute,
  InfoSlugRoute: InfoSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  OriginalsSlugRoute: OriginalsSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  TourBtsArirangRoute: TourBtsArirangRoute,
  NewsIndexRoute: NewsIndexRoute,
  OriginalsIndexRoute: OriginalsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
